feat: first steps
liven-maksim-infotecs/some_tasks pull request #1
Opened 2024-07-03 11:48 UTC by liven-maksim-infotecs

Первая версия проекта готова.

Под катом SPA и ASP.NET Core решения в рамках одного solution. На данный момент принято решение реализовать в интеграции с ASP, так как это наименее трудозатратный вариант на этом этапе. Более чем уверен, что затем последует разделение.

Была создана рыба для докера и композа. Раз мы говорим что-то про mongo и возможное разделение, то пригодится в любом случае.

2024-07-04 07:40 UTC, OksanaBelikInfotecs commented on Monitoring/ClientApp/src/app/monitoring/monitoring.component.ts
> +    http.get<DeviceStatistic[]>(baseUrl + 'api/Statistic').subscribe((result) => {
А что будет если сервера придет ошибка, такое может быть?

2024-07-04 07:40 UTC, OksanaBelikInfotecs commented on Monitoring/ClientApp/src/app/monitoring/monitoring.component.ts
> +interface DeviceStatistic {
Там вроде еще есть "Дата последней статистики"

2024-07-04 07:40 UTC, OksanaBelikInfotecs commented on Monitoring/ClientApp/src/app/home/home.component.html
> +<h1>Hello, world!</h1>
Мне кажется, что стоит удалить этот текст и написать, пусть одно предложение, но что тут происходит

2024-07-04 07:40 UTC, OksanaBelikInfotecs commented on Monitoring/ClientApp/src/app/counter/counter.component.ts
> +export class CounterComponent {
Этот компонент нужен?

2024-07-04 07:40 UTC, OksanaBelikInfotecs commented on Monitoring/ClientApp/src/app/app.component.ts
> +  title = 'app';
Это можно удалить, оно ни где не используется

2024-07-04 08:21 UTC, liven-maksim-infotecs commented on Monitoring/ClientApp/src/app/app.component.ts
> +  title = 'app';
Удалить что? Компонент? Заголовок?

2024-07-04 08:21 UTC, liven-maksim-infotecs commented on Monitoring/ClientApp/src/app/counter/counter.component.ts
> +export class CounterComponent {
Нет. Удалю

2024-07-04 08:25 UTC, liven-maksim-infotecs commented on Monitoring/ClientApp/src/app/monitoring/monitoring.component.ts
> +    http.get<DeviceStatistic[]>(baseUrl + 'api/Statistic').subscribe((result) => {
Несомненно, обработка ошибок важна.
Однако в текущей конфигурации это крайне маловероятно: страницу отдаёт сам сервис, то есть если он работает, то и страница отдаётся, а если с сервером что-то случится, то вся страница целиком не будет отдана пользователю.

2024-07-04 08:33 UTC, OksanaBelikInfotecs commented on Monitoring/ClientApp/src/app/app.component.ts
> +  title = 'app';
Я не про компонент, я про заговок (свойство title)

2024-07-04 09:30 UTC, liven-maksim-infotecs commented on Monitoring/ClientApp/src/app/app.component.ts
> +  title = 'app';
Done.

2024-07-04 09:30 UTC, liven-maksim-infotecs commented on Monitoring/ClientApp/src/app/counter/counter.component.ts
> +export class CounterComponent {
Done.

2024-07-04 09:30 UTC, liven-maksim-infotecs commented on Monitoring/ClientApp/src/app/home/home.component.html
> +<h1>Hello, world!</h1>
Done.

2024-07-04 11:47 UTC, OksanaBelikInfotecs commented on Monitoring/ClientApp/src/app/monitoring/monitoring.component.ts
> +    http.get<DeviceStatistic[]>(baseUrl + 'api/Statistic').subscribe((result) => {
Согласно, что в текущей конфигурации ошибки здесь не будет, но если вынести в prod статику на nginx, или после подключения базы и т. д. Во общем, ты все правильно понял, это был философский вопрос :)

2024-07-04 11:54 UTC, OksanaBelikInfotecs approved these changes

2024-07-04 18:08 UTC, SergerGood requested changes

2024-07-04 18:08 UTC, SergerGood commented on .gitignore
Вот это набор информации) Откуда столько?)

2024-07-04 18:08 UTC, SergerGood commented on Monitoring/ClientApp/.gitignore
Это третий файл уже кажется, не много?

2024-07-04 18:08 UTC, SergerGood commented on .npmrc
npmrc и eslint лучше на уровень клиента, они нужны только для него

2024-07-04 18:08 UTC, SergerGood commented on Monitoring/Properties/launchSettings.json
> +    "IIS Express": {
IIS нам нужен? кажется тут надо поубирать лишнее, слишком много лишнего

2024-07-04 18:08 UTC, SergerGood commented on Monitoring/appsettings.json
Наверное плохо дефолтные логи показывать только на уровне информационных. Для отладки недостаточно, давай введем прод и дев конфигурацию

2024-07-04 18:08 UTC, SergerGood commented on Monitoring/Program.cs
> +// Add services to the container.
так, комментарии в коде кажется плохой тон?)

2024-07-04 18:08 UTC, SergerGood commented on Monitoring/Dockerfile
этот файл автогенерен, а как бы ты предложил его оптимизировать?

2024-07-04 18:08 UTC, SergerGood commented on Monitoring/Monitoring.csproj
Тут конечно кошмар, хорошо что ты не сам это придумал)
Но стайлкоп  аналайзер надо все равно подключить.

2024-07-04 18:08 UTC, SergerGood commented on Monitoring/Controllers/StatisticController.cs
Добавь везде комментарии к коду по стандартам плиз

2024-07-04 18:08 UTC, SergerGood commented on Monitoring/Data/SimpleDatabase.cs
Ну что за симпл) Даже в задании это инмемори

2024-07-04 18:08 UTC, SergerGood commented on Monitoring/Data/SimpleDatabase.cs
И что за датабейс, давай названия говорящие давать

2024-07-04 18:08 UTC, SergerGood commented on Monitoring/Data/Models/Enums/DeviceOSType.cs
> +    Windows,
Windows будет по умолчанию?

2024-07-04 18:08 UTC, SergerGood commented on Monitoring/Data/Models/DeviceStatistic.cs
> +    string Username,
все поля обязательные?

2024-07-04 18:08 UTC, SergerGood commented on Monitoring/Controllers/StatisticController.cs
> +        _logger.LogInformation("Metrics have been sent: {Id}", statistic.Id);
Попробуй залогировать весь объект

2024-07-04 18:08 UTC, SergerGood commented on Monitoring/Controllers/StatisticController.cs
> +public class StatisticController : ControllerBase
Я бы для контроллера тоже более четкое название дал, а то он как будто работает с любой статистикой

2024-07-04 18:08 UTC, SergerGood commented on Monitoring/Controllers/StatisticController.cs
> +    public IEnumerable<DeviceStatistic> Get()
Мне думается GeAll здесь бы звучал более конкретно

2024-07-04 18:08 UTC, SergerGood commented on Monitoring/Data/Models/DeviceStatistic.cs
А почему у тебя модель для апи лежит в Data?

2024-07-05 05:31 UTC, liven-maksim-infotecs commented on Monitoring/Controllers/StatisticController.cs
> +        _logger.LogInformation("Metrics have been sent: {Id}", statistic.Id);
А если там какие-нибудь sensitive данные?

2024-07-05 05:38 UTC, liven-maksim-infotecs commented on .gitignore
Сгенерировал, чтобы не пропустить чего

2024-07-05 05:38 UTC, liven-maksim-infotecs commented on Monitoring/ClientApp/.gitignore
А у нас есть какое-то ограничение на их количество?)
Я думаю, это автоген при создании клиента

2024-07-05 05:39 UTC, liven-maksim-infotecs commented on .npmrc
Можно. Если клиент будет уезжать, то будет иметь смысл перенести. А пока они живут вместе, то это как общая конфигурация для всего, что может появиться в рамках.

2024-07-05 05:47 UTC, liven-maksim-infotecs commented on Monitoring/Data/Models/DeviceStatistic.cs
Потому что на данном этапе плодить отдельные модельки для разных слоёв, в том числе для API приведет только к бессмысленному бойлерплейту без явного выхлопа.

2024-07-05 06:13 UTC, liven-maksim-infotecs commented on Monitoring/Dockerfile
Я бы предложил оптимизировать, когда в этом есть потребность

2024-07-05 06:14 UTC, liven-maksim-infotecs commented on Monitoring/appsettings.json
Она и так, есть. Или вы комитите `appsettings.Development.json`?

2024-07-05 06:15 UTC, liven-maksim-infotecs commented on Monitoring/Program.cs
> +// Add services to the container.
Ну, это вкусовщина. Но если не нравится, могу убрать.

2024-07-05 06:16 UTC, liven-maksim-infotecs commented on Monitoring/Data/SimpleDatabase.cs
А ты хочешь InMemoryRepository?) Ok)

2024-07-05 06:43 UTC, liven-maksim-infotecs commented on Monitoring/Program.cs
> +// Add services to the container.
Done.

2024-07-05 06:45 UTC, liven-maksim-infotecs commented on Monitoring/Properties/launchSettings.json
> +    "IIS Express": {
Лично я не вижу зла в этой конфигурации, через compose запуск позволяет сразу поднять всё необходимое. В следующем PR так вообще там mongo появляется. Получается, эти профили используются только для локального запуска.
Но мне не критично их присутствие в полном составе. Так как IIS локально я не использую.

2024-07-05 06:46 UTC, liven-maksim-infotecs commented on Monitoring/Controllers/StatisticController.cs
Done.

2024-07-05 06:47 UTC, liven-maksim-infotecs commented on Monitoring/Data/SimpleDatabase.cs
Done.

2024-07-05 06:47 UTC, liven-maksim-infotecs commented on Monitoring/Controllers/StatisticController.cs
> +public class StatisticController : ControllerBase
Done.

2024-07-05 06:47 UTC, liven-maksim-infotecs commented on Monitoring/Controllers/StatisticController.cs
> +    public IEnumerable<DeviceStatistic> Get()
Done.

2024-07-05 06:51 UTC, liven-maksim-infotecs commented on Monitoring/Data/Models/DeviceStatistic.cs
> +    string Username,
Идентификатор обязателен и будет использоваться в будущем.
Остальные 3 логически формируют ключ для поиска конкретного устройства.

2024-07-05 06:51 UTC, liven-maksim-infotecs commented on Monitoring/Monitoring.csproj
Done.

2024-07-05 06:51 UTC, liven-maksim-infotecs commented on Monitoring/Data/Models/Enums/DeviceOSType.cs
> +    Windows,
Хорошее замечание.

2024-07-05 07:04 UTC, liven-maksim-infotecs commented on Monitoring/Data/Models/Enums/DeviceOSType.cs
> +    Windows,
Done

2024-07-05 07:04 UTC, liven-maksim-infotecs commented on Monitoring/Properties/launchSettings.json
> +    "IIS Express": {
Done.

2024-07-05 07:05 UTC, liven-maksim-infotecs commented on Monitoring/ClientApp/.gitignore
Если будет разделение, будут отдельные 2 .gitignore для конкретно клиента и для backend.
Может быть, сохранится и 1 глобальный.

2024-07-05 07:39 UTC, SergerGood commented on Monitoring/Properties/launchSettings.json
> +    "IIS Express": {
еще осталось

2024-07-05 07:39 UTC, SergerGood commented on .npmrc
договорились перенести к клиенту

2024-07-05 07:39 UTC, SergerGood commented on Monitoring/ClientApp/.gitignore
реально три

2024-07-05 07:42 UTC, SergerGood commented on Monitoring/appsettings.json
да комитем

2024-07-05 07:48 UTC, SergerGood commented on Monitoring/Dockerfile
давай все же сделаем, убрать конфигруацию и добавить опции

2024-07-05 07:54 UTC, SergerGood commented on Monitoring/Data/Models/DeviceStatistic.cs
> +    string Username,
так ты накладываешь ограничения

2024-07-05 07:55 UTC, SergerGood commented on Monitoring/Controllers/StatisticController.cs
> +        _logger.LogInformation("Metrics have been sent: {Id}", statistic.Id);
замечание верное, но просто попробовать, потому что есть ньюансы с серилогом как это надо делать

2024-07-05 07:55 UTC, SergerGood commented on Monitoring/Controllers/StatisticController.cs
> +        _logger.LogInformation("Metrics have been sent: {Id}", statistic.Id);
серилога нет, мимио

2024-07-05 09:56 UTC, SergerGood commented on Monitoring/Data/Models/DeviceStatistic.cs
Да, я поэтому задаю вопрос не почему нет второй модели, а почему она в Data. Первоначально здесь все таки апи

2024-07-05 10:03 UTC, SergerGood requested changes

2024-07-05 10:03 UTC, SergerGood commented on Monitoring/Controllers/MobileStatisticController.cs
> +        if (statistic.OsType == DeviceOSType.Unknown)
если посмотреть на UI, это нормально, что не придет тип

2024-07-05 10:03 UTC, SergerGood commented on Monitoring/Controllers/MobileStatisticController.cs
> +    /// Получить актуальную статистику по мобильному приложению.
по мобильным

2024-07-05 10:03 UTC, SergerGood commented on Monitoring/Data/Extensions/ServiceCollectionExtension.cs
> +    /// Добавить слой Data в приложение.
попридираюсь, если Data это слой, то и соответственно называться должен

2024-07-05 10:03 UTC, SergerGood commented on Monitoring/Data/MobileStatisticInMemoryRepository.cs
> +/// Простая реализация базы.
Про это мы говорили

2024-07-05 10:03 UTC, SergerGood commented on Monitoring/Data/MobileStatisticInMemoryRepository.cs
> +    /// Получить данные о статистике.
статистики чего?

2024-07-05 10:03 UTC, SergerGood commented on Monitoring/Data/Models/DeviceStatistic.cs
> +﻿namespace Monitoring.Data.Models;
а тут комментов нет

2024-07-05 10:03 UTC, SergerGood commented on Monitoring/Data/Models/Enums/DeviceOSType.cs
> +public enum DeviceOSType
И тут комментов нет

2024-07-05 10:10 UTC, liven-maksim-infotecs commented on Monitoring/Data/Models/DeviceStatistic.cs
Потому что это всё таки моделька уровня приложения. Мы храним её в "базе", а значит это не DTO. 
Короче, "доменная моделька". На выход и на хранение выглядит одинаково, поэтому необходимости в отдельных DBO- и DTO-модельках нет. Вот и находится она на уровне Data.

2024-07-05 10:12 UTC, liven-maksim-infotecs commented on Monitoring/Data/Models/DeviceStatistic.cs
Сделаю Domain

2024-07-05 10:17 UTC, liven-maksim-infotecs commented on Monitoring/Data/MobileStatisticInMemoryRepository.cs
> +/// Простая реализация базы.
Да, я ещё не залил. Созвоны.

2024-07-05 10:21 UTC, SergerGood commented on Monitoring/Data/MobileStatisticInMemoryRepository.cs
> +/// Простая реализация базы.
ты там скажи коллегам, что полностью теперь не с ними ;)

2024-07-05 11:02 UTC, liven-maksim-infotecs commented on Monitoring/Controllers/MobileStatisticController.cs
> +        if (statistic.OsType == DeviceOSType.Unknown)
Да, потому что теперь оно nullable. Но также в таком случае Uknown становится useless. Сделал по-другому.

2024-07-05 11:02 UTC, liven-maksim-infotecs commented on Monitoring/Controllers/MobileStatisticController.cs
> +    /// Получить актуальную статистику по мобильному приложению.
Done.

2024-07-05 11:03 UTC, liven-maksim-infotecs commented on Monitoring/Data/Extensions/ServiceCollectionExtension.cs
> +    /// Добавить слой Data в приложение.
Не совсем понял. А как слой сейчас называется?

2024-07-05 11:03 UTC, liven-maksim-infotecs commented on Monitoring/Data/MobileStatisticInMemoryRepository.cs
> +/// Простая реализация базы.
Done.

2024-07-05 11:03 UTC, liven-maksim-infotecs commented on Monitoring/Data/MobileStatisticInMemoryRepository.cs
> +    /// Получить данные о статистике.
Done.

2024-07-05 11:03 UTC, liven-maksim-infotecs commented on Monitoring/Data/Models/DeviceStatistic.cs
> +﻿namespace Monitoring.Data.Models;
Done.

2024-07-05 11:05 UTC, liven-maksim-infotecs commented on Monitoring/Data/Models/Enums/DeviceOSType.cs
> +public enum DeviceOSType
Done.

2024-07-05 11:05 UTC, liven-maksim-infotecs commented on .npmrc
Done.

2024-07-05 11:05 UTC, liven-maksim-infotecs commented on Monitoring/ClientApp/.gitignore
Done.

2024-07-05 11:05 UTC, liven-maksim-infotecs commented on Monitoring/Properties/launchSettings.json
> +    "IIS Express": {
Done.

2024-07-05 11:05 UTC, liven-maksim-infotecs commented on Monitoring/appsettings.json
Done.

2024-07-05 11:05 UTC, liven-maksim-infotecs commented on Monitoring/Data/Models/DeviceStatistic.cs
> +    string Username,
Done.

2024-07-05 11:06 UTC, liven-maksim-infotecs commented on Monitoring/Data/Models/DeviceStatistic.cs
Done.

2024-07-05 11:06 UTC, liven-maksim-infotecs commented on Monitoring/Controllers/MobileStatisticController.cs
> +        if (statistic.OsType == DeviceOSType.Unknown)
Done.

2024-07-05 12:18 UTC, SergerGood commented on Monitoring/appsettings.json
А он автоматом будет подхвачен, а то я запамятовал?

2024-07-05 12:20 UTC, SergerGood commented on Monitoring/Data/Models/DeviceStatistic.cs
ладно, дальше будет понятнее что да куда

2024-07-05 12:22 UTC, SergerGood commented on Monitoring/Controllers/MobileStatisticController.cs
> +        if (statistic.OsType == DeviceOSType.Unknown)
ну это кстати другой момент, у нас энам с неизвестным значением и еще и nullable. Так может не стоит их вместе использовать, что думаешь?

2024-07-05 12:25 UTC, SergerGood commented on Monitoring/Data/Extensions/ServiceCollectionExtension.cs
> +    /// Добавить слой Data в приложение.
Название метода AddData звучит как, то что мы добавляем какую-то работу с данными, причем не понятно какими, а в комментарии ты уточняешь это. Вот я намекаю на то, что метод тоже должен иметь говорящее название. Например, когда мы читаем код в Program.cs там вызов метода читается как добавление данных

```
builder.Services.AddData();
builder.Services.AddControllersWithViews();
builder.Services.AddSwaggerGen();
```

2024-07-05 12:28 UTC, SergerGood commented on Monitoring/Data/Models/Enums/DeviceOSType.cs
> +public enum DeviceOSType
у тебя проверки должны ругаться на наличие комменатрия на каждый элемент энама

2024-07-05 12:28 UTC, SergerGood commented on Monitoring/Controllers/MobileStatisticController.cs
> +        if (statistic.OsType == DeviceOSType.Unknown)
а ты убрал, ок

2024-07-05 12:30 UTC, SergerGood approved these changes

2024-07-05 12:31 UTC, SergerGood commented
Домерж этот пр в следующий, открытые комментарии доработаем в нем

2024-07-08 03:40 UTC, liven-maksim-infotecs commented on Monitoring/Data/Models/Enums/DeviceOSType.cs
> +public enum DeviceOSType
С одной стороны, да. С другой, хуже обычного перегруза комментариями - перегруз бесполезными xml-docs.

2024-07-08 03:40 UTC, merged

2024-07-08 03:42 UTC, liven-maksim-infotecs commented on Monitoring/Data/Extensions/ServiceCollectionExtension.cs
> +    /// Добавить слой Data в приложение.
А, к названию метода, согласен

2024-07-08 03:44 UTC, liven-maksim-infotecs commented on Monitoring/appsettings.json
Да, будет. По умолчанию сначала читается `appsettings.json`, за тем поверх читается и накладывается `appsettings.somename.json`, где `somename` = значению из переменной окружения `ASPNETCORE_ENVIRONMENT`

2024-07-08 07:17 UTC, SergerGood commented on Monitoring/appsettings.json
Да я вот забыл, работало оно автоматом или нет, поэтому уточнял

2024-07-08 07:19 UTC, SergerGood commented on Monitoring/Data/Models/Enums/DeviceOSType.cs
> +public enum DeviceOSType
Ну, во-первых, у нас у компании для сертификации такие правила, поэтому приходится с этим жить, а во-вторых, лучше везде, чем здесь буду, а здесь не буду. Вот это чувство прекрасного и где надо оно у всех разное и поэтому проще жить когда правило работает безусловно.