feat: Third Task implementation
liven-maksim-infotecs/some_tasks pull request #2
Opened 2024-07-04 09:14 UTC by liven-maksim-infotecs

В этом PR - имплементация третьего задания

Работа с данными выделена в отдельный проект, хранение данных теперь осуществляет mongo,  compose.yaml дополнен поднятием MongoDb, etc.

2024-07-08 06:36 UTC, OksanaBelikInfotecs commented on Monitoring.Data/IRepository.cs
> +    public Task AddAsync(T statistic, CancellationToken cancellationToken = default);
Если это обобщенный репозиторий, то лучше здесь наверно написать "entity"

2024-07-08 06:36 UTC, OksanaBelikInfotecs commented on Monitoring.Data/Extensions/ServiceCollectionExtension.cs
> +        var connectionString = configuration.GetConnectionString(ConnectionStringNames.Mongo)!;
У нас используется svacer, а он ругается на такой восклицательный знак, лучше выбрасывать исключение

2024-07-08 06:49 UTC, liven-maksim-infotecs commented on Monitoring.Data/IRepository.cs
> +    public Task AddAsync(T statistic, CancellationToken cancellationToken = default);
Да, ты права. Артефакт прошлой версии

2024-07-08 06:51 UTC, liven-maksim-infotecs commented on Monitoring.Data/Extensions/ServiceCollectionExtension.cs
> +        var connectionString = configuration.GetConnectionString(ConnectionStringNames.Mongo)!;
А почему? Это специально настроенное правило статического анализа?

2024-07-08 06:57 UTC, liven-maksim-infotecs commented on Monitoring.Data/Extensions/ServiceCollectionExtension.cs
> +        var connectionString = configuration.GetConnectionString(ConnectionStringNames.Mongo)!;
Done.

2024-07-08 06:57 UTC, liven-maksim-infotecs commented on Monitoring.Data/IRepository.cs
> +    public Task AddAsync(T statistic, CancellationToken cancellationToken = default);
Done.

2024-07-08 07:07 UTC, OksanaBelikInfotecs commented on Monitoring.Data/Extensions/ServiceCollectionExtension.cs
> +        var connectionString = configuration.GetConnectionString(ConnectionStringNames.Mongo)!;
Почему не могу сказать.

2024-07-08 07:11 UTC, OksanaBelikInfotecs commented on Monitoring.Data/Exceptions/ConnectionStringCannotBeFoundByName.cs
> +public class ConnectionStringCannotBeFoundByName : Exception
Нужны комментарии, у нас с этим строго все public и intenal сущности должны иметь комментарии

2024-07-08 07:42 UTC, SergerGood requested changes

2024-07-08 07:42 UTC, SergerGood commented on Monitoring.Web/Monitoring.Web.csproj
два csproj рядом. Это нормально или тут с отображением проблемы?

2024-07-08 07:42 UTC, SergerGood commented on Monitoring.Web/appsettings.json
У тебя и в компоузе и прод версии прописана строка подключения. Так что в итоге первично?

2024-07-08 07:42 UTC, SergerGood commented on Monitoring.Data/Monitoring.Data.csproj
> +      <HintPath>C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\6.0.31\Microsoft.Extensions.Configuration.Abstractions.dll</HintPath>
что-то пошло не так

2024-07-08 07:42 UTC, SergerGood commented on Monitoring.Data/Exceptions/ConnectionStringCannotBeFoundByName.cs
А для сего ты ввел эту ошибку, я не вижу даже ее обработки

2024-07-08 07:42 UTC, SergerGood commented on Monitoring.Data/Extensions/ServiceCollectionExtension.cs
Мне почему-о кажется что такая шутка это больше infrastructure. В дате я бы ожидал увидеть расширения больше для работы с монгой

2024-07-08 07:57 UTC, liven-maksim-infotecs commented on Monitoring.Web/appsettings.json
![image](https://github.com/liven-maksim-infotecs/some_tasks/assets/141213524/1080c81b-2fed-4cb7-bf17-7cca74c15030)
Переменные окружение подключаются последними. Значит, значения из них получаются последними и перезатерают уже имеющиеся.
compose добавляет строку подключения через объявление переменной окружения

2024-07-08 07:59 UTC, liven-maksim-infotecs commented on Monitoring.Web/Monitoring.Web.csproj
Какой-то странный артефакт работы git. Удалил лишний файл.

2024-07-08 07:59 UTC, liven-maksim-infotecs commented on Monitoring.Data/Exceptions/ConnectionStringCannotBeFoundByName.cs
> +public class ConnectionStringCannotBeFoundByName : Exception
Done

2024-07-08 08:05 UTC, liven-maksim-infotecs commented on Monitoring.Data/Exceptions/ConnectionStringCannotBeFoundByName.cs
Контракт не гарантирует, что мы получим строку подключение по имени.
Вместо получения безымянного NullReference или ArguemntNullException, приятнее, если будет выкинуто конкретное типизированное исключение с четким сообщением об ошибке.
Тем не менее, если такая ситуация возникает, то сообщение должно выкинуто.

2024-07-08 08:06 UTC, liven-maksim-infotecs commented on Monitoring.Data/Extensions/ServiceCollectionExtension.cs
так тут и так всё про работу с монгой

2024-07-08 08:06 UTC, liven-maksim-infotecs commented on Monitoring.Data/Monitoring.Data.csproj
> +      <HintPath>C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\6.0.31\Microsoft.Extensions.Configuration.Abstractions.dll</HintPath>
Done

2024-07-08 08:10 UTC, liven-maksim-infotecs commented on Monitoring.Data/Exceptions/ConnectionStringCannotBeFoundByName.cs
Если будет добавлен какой-нибудь трейсинг, например, с использованием setnry, тогда мы сможем перехватить сообщение об ошибке и оперативно разобраться, что произошло с конфигурацией

2024-07-08 09:09 UTC, SergerGood commented on Monitoring.Web/appsettings.json
я больше к тому, что имеет ли смысл держать и там и там?

2024-07-08 09:16 UTC, SergerGood commented on Monitoring.Data/Exceptions/ConnectionStringCannotBeFoundByName.cs
а ты для каких случаев планируешь использовать ошибки? только для настроек или любой логики по настройке и инициализации приложения? Почему не может быть проблем с тем чего-то еще не хватает, например в той же строке подключения? Почему например это не валидация на уровне чтения настроек?

2024-07-08 09:16 UTC, SergerGood commented on Monitoring.Data/Extensions/ServiceCollectionExtension.cs
ну ладно

2024-07-08 09:55 UTC, liven-maksim-infotecs commented on Monitoring.Web/appsettings.json
Тогда уж прод версия - это `appsettings.Production.json`.
Для меня appsettings.json - источник истины, в котором понятно, какие параметры есть, какие значения по умолчанию имеют. А все остальные конфиги - вторичны.

\+ С точки зрения общего файла конфигурации, мы не знаем, какая там мнга и где существует. Но мы знаем, что она существует, и что значение по умолчанию локалхост.
А тот же композ уже поднимает монгу и на его уровне мы точно знаем, где она

2024-07-08 10:24 UTC, liven-maksim-infotecs commented on Monitoring.Data/Exceptions/ConnectionStringCannotBeFoundByName.cs
Для любой логики.

Так они и могут быть, но это с точки зрения системы внешние данные. Поэтому исключение и бросается.

Так они читаются на инициализации, нет?

2024-07-08 11:43 UTC, SergerGood commented on Monitoring.Web/appsettings.json
ладно, я твою логику понял

2024-07-08 11:46 UTC, SergerGood commented on Monitoring.Data/Exceptions/ConnectionStringCannotBeFoundByName.cs
да, но валидировать настройки можно еще раньше, например, https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-8.0#options-validation

2024-07-08 11:47 UTC, SergerGood commented on Monitoring.Data/Exceptions/ConnectionStringCannotBeFoundByName.cs
Извиняюсь за холивар, но когда еще будет время. А вот работа с внешней библиотекой монги это не работа с внешними данными с точки зрения системы, мы же можем получить и от туда непредвиденную ошибку при инициализации?

2024-07-08 11:47 UTC, SergerGood approved these changes

2024-07-15 06:35 UTC, liven-maksim-infotecs commented on Monitoring.Data/Exceptions/ConnectionStringCannotBeFoundByName.cs
Естественно, можем упасть на инициализации из-за таких данных. И в таком случае, как и в случае с обозреваемомым , приложение развалится, так как программно мы не можем обработать неопределённое поведение. И для самой библиотеки монги могут быть данные, внешние для неё. И сама библиотека находится является частью системы "постольку поскольку": её функционал и стабильность, да и всё кодовая база лежит за пределами нашей зоны ответственности, и также может подвергаться изменению, что потенциально может привести к неопределённому поведению в будущем. Но всё-таки мы не пишем всё с 0. На это есть причина: для любой системы есть те гарантии, которые оно обеспечивает, и те нюансы, которые выходят за рамки его ответственности. Например, автор opensource библиотеки для работы с mongodb гарантирует, что не будет удалять свою библиотеку из публичного доступа, не будет вносить ломающих изменений в минорные версии, а при внесении таковых в мажёрные - оповестит в changelog. Сама библиотека архитектурно разработана для работы с mongodb и хранящимися в ней данными, и предоставляет необходимый для этого API. Такая архитектура даёт гарантии того, что нет привязки к конкретным структурам данных, и нет высокоуровневых валидаций, которые бы могли сломать взаимодействие с базой, также есть гарантии поддержки работы с определённым диапазоном версий субд. В рамках микросервисной архитектуры ситуация предоставляет больше возможностей, так как взаимодействующие между собой сервисы имеют больший шанс подпадать под нашу зону ответственности. Таким образом предлагаемые гарантии и архитектура зависит от нас, и через них мы можем добиваться необходимого нам результата.
При прочих равных условиях, если есть возможность договориться о контрактах, этот шанс надо использовать для получения необходимых гарантий. В противных случаях приходится выстраивать архитектуру с учётом тех гарантий, которые были даны.

2024-07-15 06:39 UTC, liven-maksim-infotecs commented on Monitoring.Data/Exceptions/ConnectionStringCannotBeFoundByName.cs
> да, но валидировать настройки можно еще раньше, например, https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-8.0#options-validation

Вы используете такой поход для строк подключения? Никогда не приходилось это к ним применять. Они же под капотом сами превращаются в словарь и доступны через стандартный метод работы с конфигурацией `GetConnectionString()`.

Не совсем понимаю в данном конкретном примере выигрыш от отключения стандартного подхода в пользу рукописного. Фактически ничего не поменяется: в конфигурации данные, которым мы не можем доверять, работать приложение в таком случае категорически не должно: кто его знает, куда оно там подключится и какие данные поломает.

2024-07-15 15:00 UTC, SergerGood commented on Monitoring.Data/Exceptions/ConnectionStringCannotBeFoundByName.cs
А можно я не буду продолжать холиварить?)

2024-07-15 15:00 UTC, SergerGood approved these changes

2024-07-16 06:23 UTC, merged